[package]
name = "nerdwm"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11-dl = "2.18"
chrono = "0.4"
log = "0.4"
fern = "0.6"
xdg = "2.2.0"
