[package]
name = "nerdwm"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
description = "A simple X11 window manager."
edition = "2018"
categories = ["window manager"]
license = "MIT"
repository = "https://github.com/schctl/nerdwm"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11-dl = "2.18.5"
log = "0.4.14"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

chrono = { version = "0.4.19", optional = true }
fern = { version = "0.6.0", optional = true }
xdg = { version = "2.2.0", optional = true }

[lib]
name = "nerdwm"
path = "src/lib.rs"

[features]
bin = ["fern", "xdg", "chrono"]

[[bin]]
name = "nerdwm"
path = "src/bin/nerdwm.rs"
required-features = ["bin"]
